import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { CartProvider } from "../components/CartContext";
import { WishlistProvider } from "@/components/WishlistContext";


const Inte_rfont = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${Inte_rfont.className}  antialiased`}
        >
      <WishlistProvider>
        <CartProvider>
        <main className="flex-1">{children}</main>
        <Toaster />
      </CartProvider>
    </WishlistProvider>
    </body>
  </html>
</ClerkProvider>
  );
}
